package com.github.superkiria.cbbot.main;

import java.util.Random;

public enum Stickers {

    ELEPHANT("CAACAgIAAxkBAAIMgmHkYIIXK1t9GQKHEWdV-TYXqi6bAALfAAOzkT4WSXxaFUX3xd8jBA"),
    OCTOPUS("CAACAgIAAxkBAAIMhGHkYIljoGS1eZk4lA3B4vJ7x79pAALgAAOzkT4WvHuV0iRdGsEjBA"),
    MOUSE("CAACAgIAAxkBAAIMhmHkYRVTMqs6VvAuwClUyp0KfIgZAALhAAOzkT4WOdGJ4ZP-djAjBA"),
    RHINO("CAACAgIAAxkBAAIMh2HkYS_1QhHC8HAU4vmmQHznrNRdAALjAAOzkT4Wa36POquJrRojBA"),
    TURTLE("CAACAgIAAxkBAAINdmHoYGJT9os4soSoeA7I1SRzf98bAALkAAOzkT4WBeM1--_eGZMjBA"),
    BLUE_FISH("CAACAgIAAxkBAAIMiGHkYWGJEZbzcImERxAfsvEvW5LDAALlAAOzkT4WHTpyajveNmcjBA"),
    SNAKE("CAACAgIAAxkBAAIMiWHkYYdcszOfasUioZcMICW5zN85AALmAAOzkT4WAjWI2kN29KkjBA"),
    SHEEP("CAACAgIAAxkBAAIM1mHkZOKb-LIibAy7nMQPsP_Mn1gdAALnAAOzkT4WwNMHt98af5EjBA"),
    SHARK("CAACAgIAAxkBAAIM12HkZP7SnkaMdixMhA6DpvkQhsa1AALoAAOzkT4WUn7tFG9g-fsjBA"),
    PIG("CAACAgIAAxkBAAIM2GHkZRWoaNkEzutqhVwf8_3esHrCAALpAAOzkT4WjsPOO55yBl8jBA"),
    RABBIT("CAACAgIAAxkBAAINeGHoYILam3n7Z-3cSB5_408z6lnpAALqAAOzkT4WbxxxUG1-8gABIwQ"),
    CHICKEN("CAACAgIAAxkBAAINeWHoYJtpPmg8FRZI5rsKUBQfy5KCAALrAAOzkT4WO4TohDJwLFMjBA"),
    CHINCHILLA("CAACAgIAAxkBAAINemHoYLu2b6pqdw7EaDkijOOsNV37AALsAAOzkT4WpLvMSbnFyGwjBA"),
    KOALA("CAACAgIAAxkBAAINe2HoYOWe67sUK8HB5LCcF0ff-9A4AALtAAOzkT4WI_ctHK6Gfd8jBA"),
    KIT("CAACAgIAAxkBAAINfGHoYPfQf72q_wI6WV193ZRt_5IVAALuAAOzkT4WQ0M3iK_3eAIjBA"),
    TIGER("CAACAgIAAxkBAAINfWHoYQvQSvk9NgobDCtKv_s3b-BUAALvAAOzkT4WISCmp9_0sM8jBA"),
    DOLPHIN("CAACAgIAAxkBAAINfmHoYRuw4JfJsBlr4cUB3uPnXwFCAALwAAOzkT4WZO0q-g1HvTkjBA"),
    PIRANHA("CAACAgIAAxkBAAINf2HoYTNkAAFfZ1HPmf9OcnNbJamWegAC8QADs5E-FlVdWBMDvKz4IwQ"),
    HORSE("CAACAgIAAxkBAAINgGHoYVg5jju4AT-NIdtTWpwYe6XAAALyAAOzkT4WRErGXypoxagjBA"),
    DOG("CAACAgIAAxkBAAINgWHoYckhf4M6-P6iQXmKbXT7EP02AALzAAOzkT4WS-PYl2rWJJ0jBA"),
    MONKEY("CAACAgIAAxkBAAINgmHoYfc6XvUOnYQHvmrQO_cBw3YEAAL0AAOzkT4WApRJi6G83dMjBA"),
    PENGUIN("CAACAgIAAxkBAAINg2HoYhSG-aYsDw5tVB9qOWaY3y9EAAL1AAOzkT4W0C8srD3e02ojBA"),
    LION("CAACAgIAAxkBAAINhGHoYlIKY2ErH0mP-XJkVbla6P8QAAL2AAOzkT4WFTAXxvF29_EjBA"),
    OWL("CAACAgIAAxkBAAINhWHoYmdq-FAHtxM3n2q02jcrNP1MAAL3AAOzkT4WJ0rD0A8rNPQjBA"),
    LIZARD("CAACAgIAAxkBAAINhmHoYoWuFO6VFe2XkIKFjAEmJts_AAL4AAOzkT4WH4_0nQ8INLkjBA"),
    BEE("CAACAgIAAxkBAAINh2HoYu7fcV2_IOKs2x3-vWoSXrs8AAL5AAOzkT4WETlarugoTWgjBA"),
    FROG("CAACAgIAAxkBAAINiGHoYv19otqrmGEliSWKZNWw-T3LAAL6AAOzkT4WWQbvLpYIk_sjBA"),
    APE("CAACAgIAAxkBAAINiWHoYyQ77_z2FuVaWNQVjBaXNZbxAAL7AAOzkT4Ws27yRxMTLrcjBA"),
    BAT("CAACAgIAAxkBAAINimHoYzTUwxWL5viMbi68gvtpWizWAAL8AAOzkT4WSvgPpx5bqHwjBA"),
    COW("CAACAgIAAxkBAAINi2HoY00IBWwerma-EeKWZcGdf3NYAAL9AAOzkT4Wsf3GrXQY_rEjBA"),
    EAGLE("CAACAgIAAxkBAAINjGHoY19170Ksk_62XTvG_6VoEwEFAAL-AAOzkT4WFh7ru1VTeikjBA"),
    BEAR("CAACAgIAAxkBAAINjWHoY3Aw9txyQ3rLI57jDQg0uUNFAAL_AAOzkT4Wlz0vMel6UBQjBA"),
    GOAT("CAACAgIAAxkBAAINjmHoY4FVYIytNixFOBPibulCSt_EAAMBAAKzkT4WVdiLYDvAkKUjBA"),
    SNAIL("CAACAgIAAxkBAAINj2HoY5_aI_rYj4dV5tqp6ArMVl4xAAIBAQACs5E-Fg69CXxoj4GTIwQ"),
    BOOL("CAACAgIAAxkBAAINkGHoY8jJYGOQS2w3tNkpYyAWKcwFAAICAQACs5E-FrkC9iy251BfIwQ"),
    SQUIRREL("CAACAgIAAxkBAAINkWHoY9s2RCUzrv-3WLEWko1lGEJ3AAIDAQACs5E-FiYtEHwFHOsOIwQ"),
    CROCODILE("CAACAgIAAxkBAAINkmHoY_2AI_lxLjvVdj5B7zPsOUurAAIEAQACs5E-Fh57LmFEjONAIwQ"),
    CAT("CAACAgIAAxkBAAINk2HoZCSFuo9DURPS-zXPnr-aph81AAIFAQACs5E-Fq4BRalJojH9IwQ"),
    DUCK("CAACAgIAAxkBAAINlGHoZDEP7f3fj4zFsu2AnXHE8I-TAAIGAQACs5E-FqYPsA5YEeBsIwQ"),
    CRAB("CAACAgIAAxkBAAINlWHoZER6Sy3AsIuemzvNOBauDiAuAAIHAQACs5E-Ft-pSP_HhT9dIwQ"),
    FOX("CAACAgIAAxkBAAINlmHoZF2MW2EJojqTPrTbqWQ9XvZEAAIIAQACs5E-FlEOxRVzcwg6IwQ"),
    CANCER("CAACAgIAAxkBAAINl2HoZH0wZDd5rJ7pPq7OtH-XROmZAAIJAQACs5E-FuoLlk7aE3-TIwQ"),
    DEER("CAACAgIAAxkBAAINmGHoZIwOyjKq_wPrlgjRY_cy79EhAAIKAQACs5E-FoZsSvJnoaYWIwQ"),
    GIRAFFE("CAACAgIAAxkBAAINmWHoZKlJJnLrIbyaL7AYnZayQqE5AAILAQACs5E-Fh-q6a22esYpIwQ"),
    RACCOON("CAACAgIAAxkBAAINmmHoZMIrq8O6wm9h56I6kbA-3LLIAAIMAQACs5E-Fp84Z9zCWivjIwQ")
    ;

    private static final Random random = new Random();

    private String id;

    Stickers(String s) {
        this.id = s;
    }


    public static String getRandomStickerId() {
        return Stickers.values()[random.nextInt(Stickers.values().length)].getId();
    }

    public String getId() {
        return id;
    }

}
